import { Tab, Tabs, TabList, TabPanel } from 'react-tabs';
import 'react-tabs/style/react-tabs.css';
import React from 'react';
// 
// NOTES: < <TabPanel> & <Tab> are the 2 key components. Former handles 
// content that would go into tab body while later handles Tab name. (so # 
// <Tab> instances dictate # of Tabs)

function AboutPage() {
  const displayPosts = (<Tabs>
    {/* onClick = () => { */}
    <TabList defaultIndex={1} onSelect={index => console.log(index)}>
      <Tab>ABOUT</Tab>
      <Tab>TERMS AND CONDITIONS</Tab>
    </TabList>
    <TabPanel>
      <div className="container">
        <div className="row">
          <div className="col-sm justifyText">
            <h2>COPYRIGHTS</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Consectetur purus ut faucibus pulvinar elementum. Felis eget nunc lobortis mattis aliquam. Aliquam faucibus purus in massa tempor. Fermentum leo vel orci porta. Volutpat commodo sed egestas egestas fringilla phasellus faucibus. Quis auctor elit sed vulputate mi sit. Amet risus nullam eget felis eget. Morbi tincidunt augue interdum velit euismod in pellentesque massa placerat. Nibh praesent tristique magna sit amet. Vel facilisis volutpat est velit. Sed nisi lacus sed viverra tellus in hac habitasse platea. Non pulvinar neque laoreet suspendisse interdum consectetur libero. Porta non pulvinar neque laoreet suspendisse interdum consectetur libero. Vitae proin sagittis nisl rhoncus mattis rhoncus urna. Montes nascetur ridiculus mus mauris vitae. Ultrices gravida dictum fusce ut placerat orci nulla pellentesque dignissim.</p>
            <p>Quis varius quam quisque id diam vel quam elementum. Integer eget aliquet nibh praesent. Mauris a diam maecenas sed enim ut sem viverra. Dui id ornare arcu odio ut sem nulla pharetra. Tempor commodo ullamcorper a lacus vestibulum sed. Tortor consequat id porta nibh venenatis cras. Ultrices eros in cursus turpis massa tincidunt dui ut ornare. Diam quis enim lobortis scelerisque fermentum dui faucibus in. Iaculis eu non diam phasellus. Sollicitudin ac orci phasellus egestas. Libero volutpat sed cras ornare arcu dui vivamus. Amet mattis vulputate enim nulla aliquet porttitor lacus luctus. Nec tincidunt praesent semper feugiat nibh sed. Consectetur libero id faucibus nisl tincidunt eget nullam non. Tempus imperdiet nulla malesuada pellentesque elit eget.</p>
            <p>Sed felis eget velit aliquet. Tellus rutrum tellus pellentesque eu. Morbi tristique senectus et netus et malesuada fames. Tristique et egestas quis ipsum. Non sodales neque sodales ut etiam sit amet nisl purus. Netus et malesuada fames ac turpis egestas integer. Nunc vel risus commodo viverra. Nibh venenatis cras sed felis. Id semper risus in hendrerit. Rhoncus mattis rhoncus urna neque viverra justo nec ultrices. Facilisi nullam vehicula ipsum a arcu cursus. Nunc faucibus a pellentesque sit. Blandit volutpat maecenas volutpat blandit aliquam. Non odio euismod lacinia at quis risus sed. Eget nullam non nisi est sit amet.</p>
          </div>
          <div className="col-sm marginTop justifyText">
            <p>Cras fermentum odio eu feugiat. Lobortis feugiat vivamus at augue eget arcu dictum varius duis. Viverra aliquet eget sit amet tellus cras adipiscing. Est ante in nibh mauris cursus mattis. Nisl vel pretium lectus quam id leo in vitae turpis. Pharetra pharetra massa massa ultricies mi. Amet aliquam id diam maecenas. Ut venenatis tellus in metus vulputate eu scelerisque felis. Mattis pellentesque id nibh tortor id aliquet lectus proin nibh. In iaculis nunc sed augue lacus viverra vitae congue eu. Sed euismod nisi porta lorem mollis.</p>
            <p>Nibh ipsum consequat nisl vel pretium lectus quam id. Egestas maecenas pharetra convallis posuere morbi leo urna molestie. Id volutpat lacus laoreet non. Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque. Ultrices vitae auctor eu augue ut lectus arcu bibendum. Enim nunc faucibus a pellentesque sit amet porttitor. Augue eget arcu dictum varius duis at consectetur lorem donec. Metus aliquam eleifend mi in. Imperdiet sed euismod nisi porta lorem mollis aliquam ut porttitor. Morbi quis commodo odio aenean sed adipiscing diam. Sed arcu non odio euismod. Id donec ultrices tincidunt arcu. Sed elementum tempus egestas sed sed risus. Vestibulum morbi blandit cursus risus at ultrices mi tempus. Consectetur adipiscing elit ut aliquam purus sit amet luctus. Id volutpat lacus laoreet non curabitur gravida arcu ac tortor.</p>
            <p>Vel fringilla est ullamcorper eget nulla. Feugiat pretium nibh ipsum consequat nisl vel. Facilisis magna etiam tempor orci eu lobortis elementum nibh. Nibh mauris cursus mattis molestie a iaculis. In ante metus dictum at tempor. Tellus elementum sagittis vitae et leo. Nunc congue nisi vitae suscipit. Id volutpat lacus laoreet non curabitur gravida arcu. Lacus viverra vitae congue eu consequat ac felis donec et. Nascetur ridiculus mus mauris vitae ultricies leo. Amet venenatis urna cursus eget nunc scelerisque viverra mauris. Mollis aliquam ut porttitor leo a. Congue nisi vitae suscipit tellus mauris a diam maecenas sed. Commodo viverra maecenas accumsan lacus vel facilisis volutpat est. Velit ut tortor pretium viverra suspendisse potenti nullam. Commodo ullamcorper a lacus vestibulum sed arcu. Penatibus et magnis dis parturient montes nascetur. Maecenas ultricies mi eget mauris pharetra et ultrices neque. Nec nam aliquam sem et tortor.</p>
          </div>
          <div className="col-sm marginTop justifyText">
            <p>Cursus mattis molestie a iaculis at erat pellentesque adipiscing. Arcu non odio euismod lacinia at quis risus sed. Non tellus orci ac auctor augue mauris augue. Pellentesque massa placerat duis ultricies lacus sed. Aliquet risus feugiat in ante metus dictum. Odio morbi quis commodo odio aenean sed adipiscing. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Ut faucibus pulvinar elementum integer. Nam at lectus urna duis convallis. Sit amet purus gravida quis blandit turpis. Velit ut tortor pretium viverra suspendisse potenti nullam ac tortor. At ultrices mi tempus imperdiet nulla malesuada. Sit amet mauris commodo quis imperdiet massa. </p>
            <p>Massa placerat duis ultricies lacus sed turpis. Eget mauris pharetra et ultrices neque ornare aenean. Libero nunc consequat interdum varius sit amet mattis vulputate enim. Habitant morbi tristique senectus et. Vitae semper quis lectus nulla. Ut tellus elementum sagittis vitae et leo duis. Aliquet eget sit amet tellus cras adipiscing. Enim nunc faucibus a pellentesque sit amet porttitor. Hendrerit gravida rutrum quisque non. Lacinia at quis risus sed. Feugiat nisl pretium fusce id. Elit pellentesque habitant morbi tristique senectus et netus.</p>
            <p>Tellus at urna condimentum mattis. Et sollicitudin ac orci phasellus egestas tellus rutrum. Nunc congue nisi vitae suscipit tellus. A scelerisque purus semper eget. Ac tortor vitae purus faucibus ornare suspendisse. Scelerisque felis imperdiet proin fermentum leo vel. Purus faucibus ornare suspendisse sed nisi. Eget dolor morbi non arcu risus quis varius quam. Facilisis mauris sit amet massa vitae tortor condimentum. Semper auctor neque vitae tempus quam. In nisl nisi scelerisque eu ultrices vitae auctor. Felis imperdiet proin fermentum leo vel. Fames ac turpis egestas sed tempus. Dignissim suspendisse in est ante in nibh mauris cursus. Sit amet mauris commodo quis imperdiet massa. Sodales ut etiam sit amet nisl purus in mollis nunc. Vel orci porta non pulvinar neque.</p>
          </div>
        </div>
      </div>
    </TabPanel>
    <TabPanel>
      <div class="container">
        <div class="row">
          <div className="col-sm justifyText">
            <h2>T & C</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Consectetur purus ut faucibus pulvinar elementum. Felis eget nunc lobortis mattis aliquam. Aliquam faucibus purus in massa tempor. Fermentum leo vel orci porta. Volutpat commodo sed egestas egestas fringilla phasellus faucibus. Quis auctor elit sed vulputate mi sit. Amet risus nullam eget felis eget. Morbi tincidunt augue interdum velit euismod in pellentesque massa placerat. Nibh praesent tristique magna sit amet. Vel facilisis volutpat est velit. Sed nisi lacus sed viverra tellus in hac habitasse platea. Non pulvinar neque laoreet suspendisse interdum consectetur libero. Porta non pulvinar neque laoreet suspendisse interdum consectetur libero. Vitae proin sagittis nisl rhoncus mattis rhoncus urna. Montes nascetur ridiculus mus mauris vitae. Ultrices gravida dictum fusce ut placerat orci nulla pellentesque dignissim.</p>
            <p>Quis varius quam quisque id diam vel quam elementum. Integer eget aliquet nibh praesent. Mauris a diam maecenas sed enim ut sem viverra. Dui id ornare arcu odio ut sem nulla pharetra. Tempor commodo ullamcorper a lacus vestibulum sed. Tortor consequat id porta nibh venenatis cras. Ultrices eros in cursus turpis massa tincidunt dui ut ornare. Diam quis enim lobortis scelerisque fermentum dui faucibus in. Iaculis eu non diam phasellus. Sollicitudin ac orci phasellus egestas. Libero volutpat sed cras ornare arcu dui vivamus. Amet mattis vulputate enim nulla aliquet porttitor lacus luctus. Nec tincidunt praesent semper feugiat nibh sed. Consectetur libero id faucibus nisl tincidunt eget nullam non. Tempus imperdiet nulla malesuada pellentesque elit eget.</p>
            <p>Sed felis eget velit aliquet. Tellus rutrum tellus pellentesque eu. Morbi tristique senectus et netus et malesuada fames. Tristique et egestas quis ipsum. Non sodales neque sodales ut etiam sit amet nisl purus. Netus et malesuada fames ac turpis egestas integer. Nunc vel risus commodo viverra. Nibh venenatis cras sed felis. Id semper risus in hendrerit. Rhoncus mattis rhoncus urna neque viverra justo nec ultrices. Facilisi nullam vehicula ipsum a arcu cursus. Nunc faucibus a pellentesque sit. Blandit volutpat maecenas volutpat blandit aliquam. Non odio euismod lacinia at quis risus sed. Eget nullam non nisi est sit amet.</p>
          </div>
          <div className="col-sm marginTop justifyText">
            <p>Cras fermentum odio eu feugiat. Lobortis feugiat vivamus at augue eget arcu dictum varius duis. Viverra aliquet eget sit amet tellus cras adipiscing. Est ante in nibh mauris cursus mattis. Nisl vel pretium lectus quam id leo in vitae turpis. Pharetra pharetra massa massa ultricies mi. Amet aliquam id diam maecenas. Ut venenatis tellus in metus vulputate eu scelerisque felis. Mattis pellentesque id nibh tortor id aliquet lectus proin nibh. In iaculis nunc sed augue lacus viverra vitae congue eu. Sed euismod nisi porta lorem mollis.</p>
            <p>Nibh ipsum consequat nisl vel pretium lectus quam id. Egestas maecenas pharetra convallis posuere morbi leo urna molestie. Id volutpat lacus laoreet non. Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque. Ultrices vitae auctor eu augue ut lectus arcu bibendum. Enim nunc faucibus a pellentesque sit amet porttitor. Augue eget arcu dictum varius duis at consectetur lorem donec. Metus aliquam eleifend mi in. Imperdiet sed euismod nisi porta lorem mollis aliquam ut porttitor. Morbi quis commodo odio aenean sed adipiscing diam. Sed arcu non odio euismod. Id donec ultrices tincidunt arcu. Sed elementum tempus egestas sed sed risus. Vestibulum morbi blandit cursus risus at ultrices mi tempus. Consectetur adipiscing elit ut aliquam purus sit amet luctus. Id volutpat lacus laoreet non curabitur gravida arcu ac tortor.</p>
            <p>Vel fringilla est ullamcorper eget nulla. Feugiat pretium nibh ipsum consequat nisl vel. Facilisis magna etiam tempor orci eu lobortis elementum nibh. Nibh mauris cursus mattis molestie a iaculis. In ante metus dictum at tempor. Tellus elementum sagittis vitae et leo. Nunc congue nisi vitae suscipit. Id volutpat lacus laoreet non curabitur gravida arcu. Lacus viverra vitae congue eu consequat ac felis donec et. Nascetur ridiculus mus mauris vitae ultricies leo. Amet venenatis urna cursus eget nunc scelerisque viverra mauris. Mollis aliquam ut porttitor leo a. Congue nisi vitae suscipit tellus mauris a diam maecenas sed. Commodo viverra maecenas accumsan lacus vel facilisis volutpat est. Velit ut tortor pretium viverra suspendisse potenti nullam. Commodo ullamcorper a lacus vestibulum sed arcu. Penatibus et magnis dis parturient montes nascetur. Maecenas ultricies mi eget mauris pharetra et ultrices neque. Nec nam aliquam sem et tortor.</p>
          </div>
          <div className="col-sm marginTop justifyText">
            <p>Cursus mattis molestie a iaculis at erat pellentesque adipiscing. Arcu non odio euismod lacinia at quis risus sed. Non tellus orci ac auctor augue mauris augue. Pellentesque massa placerat duis ultricies lacus sed. Aliquet risus feugiat in ante metus dictum. Odio morbi quis commodo odio aenean sed adipiscing. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Ut faucibus pulvinar elementum integer. Nam at lectus urna duis convallis. Sit amet purus gravida quis blandit turpis. Velit ut tortor pretium viverra suspendisse potenti nullam ac tortor. At ultrices mi tempus imperdiet nulla malesuada. Sit amet mauris commodo quis imperdiet massa. </p>
            <p>Massa placerat duis ultricies lacus sed turpis. Eget mauris pharetra et ultrices neque ornare aenean. Libero nunc consequat interdum varius sit amet mattis vulputate enim. Habitant morbi tristique senectus et. Vitae semper quis lectus nulla. Ut tellus elementum sagittis vitae et leo duis. Aliquet eget sit amet tellus cras adipiscing. Enim nunc faucibus a pellentesque sit amet porttitor. Hendrerit gravida rutrum quisque non. Lacinia at quis risus sed. Feugiat nisl pretium fusce id. Elit pellentesque habitant morbi tristique senectus et netus.</p>
            <p>Telllus at urna condimentum mattis. Et sollicitudin ac orci phasellus egestas tellus rutrum. Nunc congue nisi vitae suscipit tellus. A scelerisque purus semper eget. Ac tortor vitae purus faucibus ornare suspendisse. Scelerisque felis imperdiet proin fermentum leo vel. Purus faucibus ornare suspendisse sed nisi. Eget dolor morbi non arcu risus quis varius quam. Facilisis mauris sit amet massa vitae tortor condimentum. Semper auctor neque vitae tempus quam. In nisl nisi scelerisque eu ultrices vitae auctor. Felis imperdiet proin fermentum leo vel. Fames ac turpis egestas sed tempus. Dignissim suspendisse in est ante in nibh mauris cursus. Sit amet mauris commodo quis imperdiet massa. Sodales ut etiam sit amet nisl purus in mollis nunc. Vel orci porta non pulvinar neque.</p>
          </div>
        </div>
      </div>
    </TabPanel>
  </Tabs>);

  return (
    <React.Fragment>
      <div className="jumbotron">
        {displayPosts}
      </div>
    </React.Fragment>);
}



export default AboutPage;
